language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install codeclimate-test-reporter -g
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- npm run build-css
script:
- npm test -- --coverage
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  email:
    on_success: never
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: FG6xBTKKIycSyDZyhYPeX/xSXnzrfyfDeZKQnc41BecozXBFcugjGOZCY5DBeoDCLOUhQhAoaUDZuX6koEZnEtcmJ26SQGOG1XGre6qg+ppB3tyGCD8OdRXsoH8KnIeoq9QZq+zxjK4vQqWxrmXFxVLFp8+CbzGgneY5Uhkswr7kV0LU3teAeAXi5XTCB4VvNd3KoLWwrOBcGZnFFhJUwHuhTd9Bk3UAqvRWFqWdkZ0ApdmKD0lnSslQPcbFDHo2/h4E7Lr9Sk1dJLDh3xzndkefmRWs2Q1Vk9J6KFfbOwZ6jwyPs+DOnfWF6MMu61ZHRd9KVLj+B/8Jer3k0uzQqq7QqvZstUmFxYjnZ7Yu1FnCu8BZEU603/FWmi623PPRt94PTUuayrwBT8NEWo83VZ9dFsNMtQgH5sP6rBRSM4FE6uZwtz6cd2eWgNikGBODcfhQAMs2e/cyw+d1Jku9MgKBXwz70+vPaZLCUmM1J59hBPCnxWbPsP2V+62LproI8i0Ok1g3/ddcmPEmEDxfG2kftaUvVrcWyZ4n1eqphVUbjpKm3ituRdwh6r33fpGjZxwSoqwWl+2eEz6Zn/rj93XXFGa4VlMk/J5zG5q8V3tvolkWANcE/5Db0l5wre0tIlpPhNBnX4EUM2r/5eVuCtO4sMVvkdfxZZi+nq7hW84=
  app:
    develop: davemathews
